version: '3.4'

services:

  artorders_postgresql:
    image: postgres:14.1
    
  artorders_redis:
    image: redis

  artorders_rabbitmq:
    image: rabbitmq:management

  artorders_api:
    image: ${DOCKER_REGISTRY-}artordersapi
    build:
      context: .
      dockerfile: Systems/Api/ArtOrders.Api/Dockerfile
    depends_on:
      - artorders_postgresql
      - artorders_redis

  artorders_identity:
    image: ${DOCKER_REGISTRY-}artordersidentity
    build:
      context: .
      dockerfile: Systems/Identity/ArtOrders.Identity/Dockerfile
    depends_on: #Dependence (If they are not connected, then this one does not make sense)
      - artorders_postgresql
      - artorders_redis
      - artorders_api

  artorders_worker_1:
    image: ${DOCKER_REGISTRY-}artordersworker
    build:
      context: .
      dockerfile: Systems/Workers/ArtOrders.EmailSenderWorker/Dockerfile
    depends_on:
      - artorders_postgresql
      - artorders_redis
      - artorders_rabbitmq
      - artorders_api

  artorders_worker_2:
    image: ${DOCKER_REGISTRY-}artordersworker
    build:
      context: .
      dockerfile: Systems/Workers/ArtOrders.EmailSenderWorker/Dockerfile
    depends_on:
      - artorders_postgresql
      - artorders_redis
      - artorders_rabbitmq
      - artorders_api