version: '3.4'

services:
  artorders_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_artorders_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  artorders_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_artorders_net
    volumes:      
      - ~/.docker-conf/redis/data/:/data

  artorders_api:
    ports:
      - "10000:80"
    networks:
      - shared_artorders_net
    env_file:
      - env.api

  artorders_identity:
    ports:
      - "10001:80"
    networks:
      - shared_artorders_net
    env_file:
      - env.identity

networks:
  shared_artorders_net:
    name: artorders
    driver: bridge
